-- Create "orders" table
-- CREATE TABLE `orders` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `request_code` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "notifications" table
CREATE TABLE `notifications` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `phone` varchar(255) NOT NULL, `active` bool NOT NULL DEFAULT 1, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "reports" table
CREATE TABLE `reports` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "dataone" table
CREATE TABLE `dataone` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `data` json NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "password_reset_tokens" table
CREATE TABLE `password_reset_tokens` (`email` varchar(255) NOT NULL, `token` varchar(255) NOT NULL, `created_at` timestamp NULL, PRIMARY KEY (`email`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "personal_access_tokens" table
CREATE TABLE `personal_access_tokens` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `tokenable_type` varchar(255) NOT NULL, `tokenable_id` bigint unsigned NOT NULL, `name` varchar(255) NOT NULL, `token` varchar(64) NOT NULL, `abilities` text NULL, `last_used_at` timestamp NULL, `expires_at` timestamp NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `personal_access_tokens_token_unique` (`token`), INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`, `tokenable_id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "log_activities" table
CREATE TABLE `log_activities` (`id` int unsigned NOT NULL AUTO_INCREMENT, `subject` varchar(255) NOT NULL, `url` varchar(255) NOT NULL, `method` varchar(255) NOT NULL, `ip` varchar(255) NOT NULL, `agent` varchar(255) NULL, `user_id` int NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 4;
-- Create "failed_jobs" table
CREATE TABLE `failed_jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `uuid` varchar(255) NOT NULL, `connection` text NOT NULL, `queue` text NOT NULL, `payload` longtext NOT NULL, `exception` longtext NOT NULL, `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "verify_logins" table
CREATE TABLE `verify_logins` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `email` varchar(255) NOT NULL, `verification_code` varchar(255) NOT NULL, `validuntil` time NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 7;
-- Create "ipay_payments" table
CREATE TABLE `ipay_payments` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "countries" table
CREATE TABLE `countries` (`currency_code` varchar(255) NULL, `capital` varchar(255) NULL, `citizenship` varchar(255) NULL, `country_code` varchar(3) NOT NULL, `currency` varchar(255) NULL, `currency_sub_unit` varchar(255) NULL, `currency_symbol` varchar(3) NULL, `currency_decimals` int NULL, `full_name` varchar(255) NULL, `iso_3166_2` varchar(2) NOT NULL DEFAULT "", `iso_3166_3` varchar(3) NOT NULL DEFAULT "", `name` varchar(255) NOT NULL DEFAULT "", `region_code` varchar(3) NOT NULL DEFAULT "", `sub_region_code` varchar(3) NOT NULL DEFAULT "", `eea` bool NOT NULL DEFAULT 0, `calling_code` varchar(3) NULL, `flag` varchar(6) NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`country_code`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "password_resets" table
CREATE TABLE `password_resets` (`email` varchar(255) NOT NULL, `token` varchar(255) NOT NULL, `created_at` timestamp NULL, INDEX `password_resets_email_index` (`email`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "migrations" table
CREATE TABLE `migrations` (`id` int unsigned NOT NULL AUTO_INCREMENT, `migration` varchar(255) NOT NULL, `batch` int NOT NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 28;
-- Create "document_types" table
CREATE TABLE `document_types` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `code` varchar(255) NOT NULL, `type` varchar(255) NOT NULL, `is_active` bool NOT NULL DEFAULT 1, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 4;
-- Create "certificates" table
CREATE TABLE `certificates` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `serial_number` text NOT NULL, `document_type_id` bigint unsigned NOT NULL, `first_name` text NOT NULL, `last_name` text NOT NULL, `year_of_graduation` text NOT NULL, `course_name` text NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `certificates_document_type_id_foreign` (`document_type_id`), CONSTRAINT `certificates_document_type_id_foreign` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "localizations" table
CREATE TABLE `localizations` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `localization_type` varchar(255) NOT NULL, `active` bool NOT NULL DEFAULT 1, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 2;
-- Create "charges" table
CREATE TABLE `charges` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `localization_id` bigint unsigned NOT NULL, `document_type_id` bigint unsigned NOT NULL, `amount` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `charges_document_type_id_foreign` (`document_type_id`), INDEX `charges_localization_id_foreign` (`localization_id`), CONSTRAINT `charges_document_type_id_foreign` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `charges_localization_id_foreign` FOREIGN KEY (`localization_id`) REFERENCES `localizations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "diplomas" table
CREATE TABLE `diplomas` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `serial_number` text NOT NULL, `document_type_id` bigint unsigned NOT NULL, `first_name` text NOT NULL, `last_name` text NOT NULL, `year_of_graduation` text NOT NULL, `course_name` text NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `diplomas_document_type_id_foreign` (`document_type_id`), CONSTRAINT `diplomas_document_type_id_foreign` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "higher_diplomas" table
CREATE TABLE `higher_diplomas` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `serial_number` text NOT NULL, `document_type_id` bigint unsigned NOT NULL, `first_name` text NOT NULL, `last_name` text NOT NULL, `year_of_graduation` text NOT NULL, `course_name` text NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `higher_diplomas_document_type_id_foreign` (`document_type_id`), CONSTRAINT `higher_diplomas_document_type_id_foreign` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "roles" table
CREATE TABLE `roles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `role_name` varchar(255) NOT NULL, `is_active` bool NOT NULL DEFAULT 1, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 2;
-- Create "users" table
CREATE TABLE `users` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `role_id` bigint unsigned NOT NULL, `first_name` varchar(255) NOT NULL, `last_name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `email_verified_at` timestamp NULL, `password` varchar(255) NOT NULL, `phone_number` varchar(255) NOT NULL, `field` varchar(255) NOT NULL, `is_active` bool NOT NULL DEFAULT 1, `remember_token` varchar(100) NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE INDEX `users_email_unique` (`email`), INDEX `users_role_id_foreign` (`role_id`), CONSTRAINT `users_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "payment_methods" table
CREATE TABLE `payment_methods` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `method` varchar(255) NOT NULL, `meta` json NOT NULL, `active` bool NOT NULL, `updated_by` bigint unsigned NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `payment_methods_updated_by_foreign` (`updated_by`), CONSTRAINT `payment_methods_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "verifications" table
CREATE TABLE `verifications` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `verification_code` varchar(255) NOT NULL, `localization_id` bigint unsigned NOT NULL, `document_type_id` bigint unsigned NOT NULL, `year_of_graduation` varchar(255) NOT NULL, `serial_no` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `phone` varchar(255) NOT NULL, `vdate` varchar(255) NOT NULL, `file_link` varchar(255) NOT NULL, `approved` int NOT NULL DEFAULT 0 COMMENT "0 => new request, 1=> for approved, 2=> for rejected", `found_in_db` bool NOT NULL DEFAULT 0, `is_paid` bool NOT NULL DEFAULT 0, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `verifications_document_type_id_foreign` (`document_type_id`), INDEX `verifications_localization_id_foreign` (`localization_id`), CONSTRAINT `verifications_document_type_id_foreign` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `verifications_localization_id_foreign` FOREIGN KEY (`localization_id`) REFERENCES `localizations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "revenues" table
CREATE TABLE `revenues` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `verification_id` bigint unsigned NOT NULL, `request_code` varchar(255) NOT NULL, `invoiced_amount` varchar(255) NOT NULL, `localization_id` bigint unsigned NOT NULL, `time_paid` varchar(255) NULL, `amount_paid` varchar(255) NULL, `transaction_code` varchar(255) NULL, `payment_method` varchar(255) NULL, `paying_phone` varchar(255) NULL, `ipay_status` varchar(255) NULL, `msidn` varchar(255) NULL, `rdate` varchar(255) NULL, `card_mask` varchar(255) NULL, `merchant_request_id` varchar(255) NULL, `checkout_request_id` varchar(255) NULL, `mpesa_receipt_code` varchar(255) NULL, `result_code` varchar(255) NULL, `result_desc` varchar(255) NULL, `is_reversed` bool NOT NULL DEFAULT 0, `is_paid` int NULL DEFAULT 0 COMMENT "0 => new request, 1=> for paid, 2=> for failed", `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `revenues_localization_id_foreign` (`localization_id`), INDEX `revenues_verification_id_foreign` (`verification_id`), CONSTRAINT `revenues_localization_id_foreign` FOREIGN KEY (`localization_id`) REFERENCES `localizations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `revenues_verification_id_foreign` FOREIGN KEY (`verification_id`) REFERENCES `verifications` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "permissions" table
CREATE TABLE `permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `guard_name` varchar(255) NOT NULL, `read_name` varchar(255) NOT NULL, `module` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 56;
-- Create "role_has_permissions" table
CREATE TABLE `role_has_permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `role_id` bigint unsigned NOT NULL, `permission_id` bigint unsigned NOT NULL, `is_active` bool NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `role_has_permissions_permission_id_foreign` (`permission_id`), INDEX `role_has_permissions_role_id_foreign` (`role_id`), CONSTRAINT `role_has_permissions_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `role_has_permissions_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 56;
-- Create "departments" table
CREATE TABLE `departments` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `department_code` varchar(255) NOT NULL, `department_name` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "transcripts" table
CREATE TABLE `transcripts` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `department_id` bigint unsigned NOT NULL, `document_type_id` bigint unsigned NOT NULL, `serial_no` varchar(255) NOT NULL, `first_name` varchar(255) NOT NULL, `last_name` varchar(255) NOT NULL, `course_name` varchar(255) NOT NULL, `year_of_graduation` varchar(255) NOT NULL, `year_of_admission` varchar(255) NOT NULL, `year_of_completion` varchar(255) NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `transcripts_department_id_foreign` (`department_id`), INDEX `transcripts_document_type_id_foreign` (`document_type_id`), CONSTRAINT `transcripts_department_id_foreign` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `transcripts_document_type_id_foreign` FOREIGN KEY (`document_type_id`) REFERENCES `document_types` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- Create "user_has_permissions" table
CREATE TABLE `user_has_permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `user_id` bigint unsigned NOT NULL, `permission_id` bigint unsigned NOT NULL, `is_active` bool NOT NULL, `created_at` timestamp NULL, `updated_at` timestamp NULL, PRIMARY KEY (`id`), INDEX `user_has_permissions_permission_id_foreign` (`permission_id`), INDEX `user_has_permissions_user_id_foreign` (`user_id`), CONSTRAINT `user_has_permissions_permission_id_foreign` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_has_permissions_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci AUTO_INCREMENT 56;
